// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_API_KEY', fallback: ''),
    appId: '1:152625161723:web:7b2ddded9aec7ce82b175e',
    messagingSenderId: '152625161723',
    projectId: 'care-chat-386021',
    authDomain: 'care-chat-386021.firebaseapp.com',
    storageBucket: 'care-chat-386021.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY', fallback: ''),
    appId: '1:152625161723:android:1f1adecb0f6053092b175e',
    messagingSenderId: '152625161723',
    projectId: 'care-chat-386021',
    storageBucket: 'care-chat-386021.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_API_KEY', fallback: ''),
    appId: '1:152625161723:ios:bac7843bbce7b8d02b175e',
    messagingSenderId: '152625161723',
    projectId: 'care-chat-386021',
    storageBucket: 'care-chat-386021.appspot.com',
    iosClientId:
        '152625161723-cf2aomq486j9ktj2oq6m65rk1pga7mu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.careChatApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_MACOS_API_KEY', fallback: ''),
    appId: '1:152625161723:ios:bac7843bbce7b8d02b175e',
    messagingSenderId: '152625161723',
    projectId: 'care-chat-386021',
    storageBucket: 'care-chat-386021.appspot.com',
    iosClientId:
        '152625161723-cf2aomq486j9ktj2oq6m65rk1pga7mu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.careChatApp',
  );
}
